language: node_js
node_js:
- v6.11.1
before_install:
- sudo pip install virtualenv
- virtualenv my_project
- source my_project/bin/activate
before_script:
- npm install -g gitbook-cli@2.3.0
script: bash ./deploy.sh
after_success:
- rm -rf _book/my_project
- pip install git+https://github.com/dtolb/s3-deploy-website.git
- s3-deploy-website "bw-apdocs"
env:
  global:
  - ENCRYPTION_LABEL: 34fb19845977
  - COMMIT_AUTHOR_EMAIL: developerhelp@bandwidth.com
  - secure: ur/c/Fq7qDKRQ5Gxbvv+AGGy0jHEg78tic7ztswRANE7Lt81H7yunT+fGD7/tDRKaRJ7FMnxNGNcMmAo6FV23IyeeZk5XnhpxpAVbwA9IGKsU4SV2ZyyrhMIIm1VqVsVvCpymjmU0EBL07ihfaQUgHDGDxCNSK9PyNmHO2vJ52xbCF4TrB+mpqBpNST99FCO7F6MLyYuO9O4SbwU7K/wHyKSUsfDtdYVt1I1LA02neai+0A8hftcVXwGaHc+VhOeKYYr3/+wlVPhZ6WPOwaJZUwEDK9sPouRYrDBFFCEPPlMwKnlFyVg7pxJ38yVatgFkkeeJ3+s5mXDj//t+3t5/oA3JlSxbgEkLR2Rt1oqwklc64n21S8n9RZFKqVDziGSsl3sQeVlri2K5zipS1/oIJ7LKTPDCitM7NEIRc5x6ZuebUWqLJUIsOL9hRJeiC5zS4eoI6hlS8FUAWN0ejaHjp/b+NymnkChmbTI04Tc3WMzAXKy8jWcZWjoeX4UsS3hZlwMr6X9zIztJsiij5rm58uAlXnHh85fzCF7mesxZ0Rapq/obO51SJ2ZxRTAjV31fkVLtVbgrx7gPSsqD+iLP7bRJLFgGPXqv61m5hxTAuKZ4TXMWraFX2K5QXvHxbX5J7xY5sEFo3kQ/HdtpoMua7PnL1Crmeb2qR8CZGO3Xoc=
  - secure: luPxNy7FRJCdx2a+NaQbhZ/lPekzO+MbFKANRki7nCWtZ0+22IHVKb0EgDyXtNfz4CGGewVW7rRZhIIG5Dtsk43BP2dG/WWjXIrIOQMh/plBxBWz5KpcDdBqYlAl6DwuTyj/3pAqYSZaOTu9IhnvsipFn7LnmN3920b/69TtuXt13BlG0CaLW/nxH0bDX9SfHF7VZilRZ4Ui7VZ2tG0QGzJjyZN/3ub54wlAYllG3dqEI7plNvIJTUsE9v+0IvIb0kNQoZUML2kueofwpAT0jSJYMV2ooPWDCQveHTWFSp6Wtgl9SfD6I5C8Ne19QfosGVAR7k1yPU5wiz4SVadrXf0A6BGbB5HLyCnYRDSHKYtnxyECaOKi/mEVUi7i0C8/tYsizZtv3aj4y4mTLEfofFjAMfEW6yiImf0yb+hcQ/OEgE4IDdIpsyEK3aLLqmE89sS2X2tqkQNRlt2bly526XVR7ythgcel71AFAtCvu5eCMRqhty0WMA/lnQ8d3WLV1Imcg1PoUAHI6l8r8Fei0CG5CV9nzCgUOnzxz298Z6OwU5VrhlNCBQ+/glirycFYoYj2YVeaDivY8bEkpeGAecGQjyn1/pouBTYGmcJeHuHh4ExJU1uiq1EBik2GE35d/nEXehLpc4r926dGZxIzVKG/2RlNaMPjcW2aLNpOkIY=
